name: Deploy Mesop Web App

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - "projects/rag/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "FILE_SERVER_URI=${{ secrets.FILE_SERVER_URI }}" >> .env
          echo "FILE_SERVER_USERNAME=${{ secrets.FILE_SERVER_USERNAME }}" >> .env
          echo "FILE_SERVER_PASSWORD=${{ secrets.FILE_SERVER_PASSWORD }}" >> .env

      - name: Copy repository to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.MESOP_HOST }}
          username: github
          key: ${{ secrets.MESOP_KEY }}
          source: ./monorepo/projects/rag
          target: ~/rag

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.MESOP_HOST }}
          username: github
          key: ${{ secrets.MESOP_KEY }}
          script: |
            cd ~/rag
            docker compose build
            docker compose down
            docker compose up -d
